# update the package index
FROM pyar6329/haskell:8.6.4-base AS stack-update-cron

RUN set -x && \
  stack --no-terminal update

# update the package index
FROM pyar6329/haskell:8.6.5-llvm-base AS stack-llvm-update-cron

RUN set -x && \
  stack --no-terminal update
