name: Publish Docker
on:
  push:
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sundays at 02:00
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        ghc: ['8.6.5', '8.6.4']
    env:
      DOCKER_BUILDKIT: 1
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Publish to Docker Registry ${{ matrix.ghc }}-base
      uses: docker/build-push-action@v1
      if: ${{ github.event_name != 'schedule' }}
      with:
        repository: pyar6329/haskell
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        push: ${{ github.ref == 'refs/heads/master' }}
        tags: ${{ matrix.ghc }}-base
        target: haskell-base
        dockerfile: ${{ matrix.ghc }}/Dockerfile

    - name: Publish to Docker Registry ${{ matrix.ghc }}
      uses: docker/build-push-action@v1
      with:
        repository: pyar6329/haskell
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        push: ${{ github.ref == 'refs/heads/master' }}
        tags: ${{ matrix.ghc }}
        target: stack-update
        dockerfile: ${{ matrix.ghc }}/Dockerfile

